### PR TITLE
Added weekdayofmonth

### LINKED ISSUE #6: Implement task type "weekdayofmonth"
Currently cases like "Every first Monday of the month" are not covered by the task types.

### PR DESCRIPTION
**Pull request by besnardf**
Fixes https://github.com/error401de/recurring-tasks/issues/6

### CODE REVIEW

**Comment by error401de** [comment]
Thanks a lot! There is currently a potentially conflicting PR review ongoing, I will check this one afterwards.

**Comment by error401de** [comment]
Hi @besnardf 
the other PR is merged. Would you like to resolve the conflict?
Thanks!

**Comment by besnardf** [comment]
Hi @error401de 
It should be all good now !

**Comment by error401de** [comment]
Awesome, thank you so much! I fixed 2 little syntax errors and merged.
happy hacktoberfesting!

**Pull request merged**
