### PR TITLE
Logging

### LINKED ISSUE #5: Logging
Logs of triggered notifications and errors would be nice

### PR DESCRIPTION
**Pull request by Paola351**
Fixes #5

### CODE REVIEW

**Comment by Paola351** [comment]
sorry, never did a rebase from another fork :D it should be ok

**Comment by error401de** [comment]
Where does the logs go to?
Seems like the path configuration is missing.
Furthermore type daily throws an error (checked only that and weekly so far)

**Comment by Paola351** [comment]
> Where does the logs go to?
> Seems like the path configuration is missing.
> Furthermore type daily throws an error (checked only that and weekly so far)

Since it was not specified I leaved them into standard output (the console). I can add the file i you want! Which error does it throw? The one on the log

**Comment by error401de** [comment]
Mmh I did not see it in the console either. But anyway: A logfile would be awesome for issue investigation :)
Error I get:
```
python3 checkTasks.py
Traceback (most recent call last):
  File "checkTasks.py", line 69, in <module>
    logging.info("Everything is OK! :D I'll remember you \"{}\" every day " % message)
TypeError: not all arguments converted during string formatting
```
But I suggest we wait for the finalisation of the other open PR (9) - An additional task type is implemented there. This way the logging could be implemented for all checks at one time - WDYT?

**Comment by Paola351** [comment]
> A logfile would be awesome for issue investigation :)

No problem, i fixed the error and added the logfile in the meanwhile. Do you want me to log even the checks as debug messages? :D

**Comment by error401de** [comment]
Thanks, I already merged it! :)
I will just slightly change the logging messages and delete the empty lines.
Not sure what you mean with the additional logging, can you explain more detailed? :)
Thanks again!

**Comment by Paola351** [comment]
> Thanks, I already merged it! :)
> I will just slightly change the logging messages and delete the empty lines.
> Not sure what you mean with the additional logging, can you explain more detailed? :)
> Thanks again!

I added a logging.ini to configure the logger, i can open a new pullrequest if you want. could you please add the label: hacktoberfest-accepted to the merged pr? :D (Please add it even on the other one :D)

**Comment by error401de** [comment]
Logger.ini sounds nice, feel free to create an additional PR! :)
As I merged the PR it should already count into your hacktoberfest PRs - still I just added the label though ;)

**Pull request merged**
