### PR TITLE
Added validations

### LINKED ISSUE #4: Validation of task configurations
Currently the configurations in tasks.ini are not validated, so wrong values could crash the script.
Errors in config should result into a warning via email.

### PR DESCRIPTION
**Pull request by Paola351**
Fixes #4

### CODE REVIEW

**Review by error401de — CHANGES_REQUESTED** [review]
Thanks a lot so far!
Seems like % templating in the output is not working, could you recheck?

```python3 checkTasks.py
Traceback (most recent call last):
  File "checkTasks.py", line 44, in <module>
    validate_task_type(taskType)
  File "checkTasks.py", line 19, in validate_task_type
    raise ValueError("Sorry, taskType should only be in {}" % taskTypeList)
ValueError: Sorry, taskType should only be in {}

**Comment by Paola351** [comment]
> Thanks a lot so far!
> Seems like % templating in the output is not working, could you recheck?
> 
> ```python
> Traceback (most recent call last):
>   File "checkTasks.py", line 44, in <module>
>     validate_task_type(taskType)
>   File "checkTasks.py", line 19, in validate_task_type
>     raise ValueError("Sorry, taskType should only be in {}" % taskTypeList)
> ValueError: Sorry, taskType should only be in {}
> ```

Sorry, I thought i tested that but it seems it's not the case, now should be ok.

**Review by error401de — CHANGES_REQUESTED** [review]
We're almost there! :)
Below `if taskType == 'yearly':` you define `month` and `day`.
This leads to an error if the validation is successful, so the variables should be renamed.

Furthermore in line 19 you use a `.` in front of `format` but in line 19 it's a `,` (and in line 24 there is a space inbetween). I did not check for impact so far, but I guess one of those is wrong?

Thanks!

**Comment by Paola351** [comment]
> We're almost there! :)
> Below `if taskType == 'yearly':` you define `month` and `day`.
> This leads to an error if the validation is successful, so the variables should be renamed.
> 
> Furthermore in line 19 you use a `.` in front of `format` but in line 19 it's a `,` (and in line 24 there is a space inbetween). I did not check for impact so far, but I guess one of those is wrong?
> 
> Thanks!

spaces are not a problem when invoking a method while the commas.... I really don't know here my mind is today, I'm really unforgivable!
In the other pullrequest i extracted some methods to avoid the duplication of the keywords... i you want to renamed that, in this way, you have to change them only in those methods :D

**Review by error401de — APPROVED** [review]

**Comment by error401de** [comment]
Works, thanks a lot! :)

**Pull request merged**
